---
abstract: 'Backup files/directories with histories, using rsync'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Slurp: 0
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-RsyBak
requires:
  File::Flock: 0
  File::Path: 2.08
  File::Which: 0
  File::chdir: 0
  Log::Any: 0
  Perinci::CmdLine: 0
  Rinci: v1.1.40
  String::ShellQuote: 0
  perl: 5.010001
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=File-RsyBak
  homepage: https://metacpan.org/release/File-RsyBak
  repository: git://github.com/sharyanto/perl-File-RsyBak.git
version: 0.19
